# Generated by Django 6.0.3 on 2026-03-28 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('school', models.CharField(max_length=200, verbose_name='Школа/колледж')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('motivation', models.TextField(blank=True, verbose_name='Почему inVision U?')),
                ('achievement', models.TextField(blank=True, verbose_name='Главное достижение')),
                ('problem', models.TextField(blank=True, verbose_name='Проблема которую хочешь решить')),
                ('future', models.TextField(blank=True, verbose_name='Планы на 5 лет')),
                ('essay', models.TextField(blank=True, verbose_name='Эссе')),
                ('essay_file', models.FileField(blank=True, null=True, upload_to='essays/', verbose_name='Файл эссе')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('scoring', 'Оценивается'), ('scored', 'Оценён'), ('shortlisted', 'Шортлист'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_score', models.FloatField(default=0, verbose_name='Мотивация')),
                ('leadership_score', models.FloatField(default=0, verbose_name='Лидерство')),
                ('authenticity_score', models.FloatField(default=0, verbose_name='Аутентичность')),
                ('growth_score', models.FloatField(default=0, verbose_name='Рост')),
                ('total_score', models.FloatField(default=0, verbose_name='Итого')),
                ('ai_detected', models.BooleanField(default=False, verbose_name='AI обнаружен')),
                ('ai_probability', models.FloatField(default=0, verbose_name='Вероятность AI (0-1)')),
                ('summary', models.TextField(blank=True, verbose_name='Резюме')),
                ('strengths', models.JSONField(default=list, verbose_name='Сильные стороны')),
                ('red_flags', models.JSONField(default=list, verbose_name='Красные флаги')),
                ('recommendation', models.CharField(blank=True, max_length=20, verbose_name='Рекомендация')),
                ('raw_response', models.JSONField(default=dict, verbose_name='Сырой ответ Claude')),
                ('scored_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
