# Generated by Django 6.0.3 on 2026-04-04 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Смена статуса'), ('comment', 'Комментарий'), ('rescore', 'Переоценка'), ('view', 'Просмотр')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Лог действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
