# Generated by Django 6.0.3 on 2026-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='submit_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток отправки'),
        ),
    ]
